-- CreateTable
CREATE TABLE "ReedHistory" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "state" TEXT NOT NULL,
    "timestamp" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "reedId" INTEGER NOT NULL,
    FOREIGN KEY ("reedId") REFERENCES "Reed" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
